### ISSUE TITLE
Cannot run tests

### ISSUE THREAD

**Issue by adamreisnz** [SabakiHQ/deadstones#8]
Hi, I've followed the instructions in the Readme and installed all the tools. Building the wasm works fine.
However, running `npm test` fails with the following error:

```
 Cannot find module './reports/base'
Require stack:
- /node_modules/jackspeak/noop.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
    at resolveFileName (/node_modules/tap/node_modules/resolve-from/index.js:17:39)
    at resolveFrom (/node_modules/tap/node_modules/resolve-from/index.js:31:9)
    at module.exports (/node_modules/tap/node_modules/resolve-from/index.js:34:41)
    at importJsx (/node_modules/tap/node_modules/import-jsx/index.js:23:21)
    at module.exports (/node_modules/tap/node_modules/treport/lib/index.js:11:18)
    at exports.makeReporter (/node_modules/tap/bin/run.js:383:23)
    at runTests (/node_modules/tap/bin/run.js:693:3)
    at main (/node_modules/tap/bin/run.js:240:5)
    at Object.j.main (/node_modules/jackspeak/index.js:483:5) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/node_modules/jackspeak/noop.js' ]
}
```

This is on OS X Sonoma 14.2.1 with Node version 21.1.0

**Comment by apetresc** [comment]
Fixed in #12 (released in 2.2.0). It's tap's CLI that breaks on modern Node, so `npm test` now runs each suite with `node` directly -- `npm install && npm run build && npm test` should be clean now. Thanks for the report @adamreisnz.
